### ISSUE TITLE
This code can not run in my pc

### ISSUE THREAD

**Issue by yuyijie1995** [ChaofWang/L-GM_loss_pytorch#2]
Launching pytest with arguments D:/LGMloss_python/L-GM_loss_pytorch/test_loss.py in D:\LGMloss_python\L-GM_loss_pytorch

============================= test session starts =============================
platform win32 -- Python 3.6.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: D:\LGMloss_python\L-GM_loss_pytorch, inifile:collected 0 items

======================== no tests ran in 2.07 seconds =========================

Process finished with exit code 

I do not know what is wrong

**Comment by ChaofWang** [comment]
I don't understand your error message, I guess it may be a problem with the execution path or platform.My pytorch version is 0.4.1 and python is 3.5. There is no problem testing this code on win10 and Ubuntu 16.04.
